services:
  db:
    image: kartoza/postgis:latest
    ports:
        - ${POSTGRES_PORT}:5432
    environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
        - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
        - FORCE_SSL=TRUE
    restart: on-failure
    healthcheck:
      test: "pg_isready -h 127.0.0.1 -U ${POSTGRES_USER}"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASS}
      - DB_DATABASE=${POSTGRES_DB}
      - GS_NO_SIGN_REQUEST=YES
      - AWS_NO_SIGN_REQUEST=YES
      - AWS_DEFAULT_REGION=af-south-1
      - JUPYTER_PORT=${JUPYTER_PORT}
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    ports:
      - ${JUPYTER_PORT}:${JUPYTER_PORT}
    volumes:
      - ./products:/home/jovyan/products
      - ./notebooks:/home/jovyan/notebooks
      - ./services:/home/jovyan/services
      - ./ruff.toml:/home/jovyan/ruff.toml

    depends_on:
        db:
          condition: service_healthy
    restart: always

  explorer:
    image: ghcr.io/opendatacube/explorer:2.12.4
    environment:
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASS}
      - DB_DATABASE=${POSTGRES_DB}
      - FLASK_ENV=development
      - FLASK_APP=cubedash
      - FLASK_DEBUG=1
      - CUBEDASH_DEFAULT_TIMEZONE=${CUBEDASH_DEFAULT_TIMEZONE}
      - GS_NO_SIGN_REQUEST=YES
      - AWS_NO_SIGN_REQUEST=YES
      - CUBEDASH_DATA_S3_REGION="af-south-1"
      - AWS_S3_ENDPOINT=https://s3.af-south-1.amazonaws.com
      # - VIRTUAL_HOST=datacube.explorer
    depends_on:
      - db
    ports:
      - ${EXPLORER_PORT}:8080

  ows:
    image: opendatacube/ows:1.8.42.post20_gaa67e0be
    environment:
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASS}
      - DB_DATABASE=${POSTGRES_DB}
      - AWS_DEFAULT_REGION=af-south-1
      - AWS_NO_SIGN_REQUEST=YES
      - PYTHONPATH=/env/config
      - DATACUBE_OWS_CFG=ows_refactored.dev_af_ows_root_cfg.ows_cfg
    ports:
      - "8083:8000"
    volumes:
       - ./services/ows_refactored:/env/config/ows_refactored/
       - ./services/inventory:/env/config/inventory/
    depends_on:
      db:
        condition: service_healthy
