services:
  db:
    image: kartoza/postgis:latest
    ports:
        - ${POSTGRES_PORT}:5432
    environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
        - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
        - FORCE_SSL=TRUE
    restart: on-failure
    healthcheck:
      test: "pg_isready -h 127.0.0.1 -U ${POSTGRES_USER}"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # $ODC_{environment name}_{option name}
      - ODC_DEFAULT_INDEX_DRIVER=postgis
      # Database connection URL: postgresql://<username>:<password>@<hostname>:<port>/<database>
      - ODC_DEFAULT_DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@db:5432/${POSTGRES_DB}
      - GS_NO_SIGN_REQUEST=YES
      - AWS_NO_SIGN_REQUEST=YES
      - AWS_DEFAULT_REGION=af-south-1
      - JUPYTER_PORT=${JUPYTER_PORT}
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    ports:
      - ${JUPYTER_PORT}:${JUPYTER_PORT}
    volumes:
      - ./products:/home/jovyan/products
      - ./notebooks:/home/jovyan/notebooks
      - ./services:/home/jovyan/services
      - ./ruff.toml:/home/jovyan/ruff.toml

    depends_on:
        db:
          condition: service_healthy
    restart: always

  explorer:
    image: opendatacube/explorer:3.1.0-49-g8fc48b0a
    environment:
      # $ODC_{environment name}_{option name}
      - ODC_DEFAULT_INDEX_DRIVER=postgis
      # Database connection URL: postgresql://<username>:<password>@<hostname>:<port>/<database>
      - ODC_DEFAULT_DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@db:5432/${POSTGRES_DB}
      - FLASK_ENV=development
      - FLASK_APP=cubedash
      - FLASK_DEBUG=1
      - CUBEDASH_DEFAULT_TIMEZONE=${CUBEDASH_DEFAULT_TIMEZONE}
      - GS_NO_SIGN_REQUEST=YES
      - AWS_NO_SIGN_REQUEST=YES
      - CUBEDASH_DATA_S3_REGION="af-south-1"
      - AWS_S3_ENDPOINT=https://s3.af-south-1.amazonaws.com
      # - VIRTUAL_HOST=datacube.explorer
    depends_on:
      - db
    ports:
      - ${EXPLORER_PORT}:8080

  ows:
    # image: ghcr.io/opendatacube/ows:develop
    image: ghcr.io/opendatacube/ows:1.9.11
    environment:
      - ODC_ENVIRONMENT=default
      - ODC_DEFAULT_INDEX_DRIVER=postgis
      - ODC_DEFAULT_DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@db:5432/${POSTGRES_DB}
      - AWS_DEFAULT_REGION=af-south-1
      - AWS_NO_SIGN_REQUEST=YES
      - PYTHONPATH=/env/config
      - DATACUBE_OWS_CFG=ows_refactored.dev_af_ows_root_cfg.ows_cfg
    ports:
      - "8083:8000"
    volumes:
       - ./services/ows_refactored:/env/config/ows_refactored/
       - ./services/inventory:/env/config/inventory/
    depends_on:
      db:
        condition: service_healthy
