name: datacube-ows-env
channels:
  - conda-forge
dependencies:
  # base
  - python=3.12.3
  - gdal
  - libgdal
  - libgdal-arrow-parquet
  - postgresql
  # datacube + optional dependencies
  - datacube>=1.9.0
  - boto3
  - botocore
  - bottleneck
  - ciso8601
  # ODC ecosystem libraries
  - eodatasets3
  - odc-apps-dc-tools>=1.9.5
  - odc-cloud
  - aiobotocore[boto3]
  - odc-dscache
  - odc-geo
  - odc-loader
  - odc-stac
  # dask + extras
  - dask
  - distributed
  - lz4
  # fsspec + extras
  - fsspec
  - gcsfs
  - s3fs
  # xarray + extras
  - xarray
  - cftime
  - opt_einsum
  - flox
  - h5netcdf
  - netCDF4
  - numba
  - numbagg
  - pooch
  - pydap
  - zarr
  # Jupyter
  - jupytergis 
  - qgis
  - jupyterlab_iframe
  - jupyter-resource-usage
  - nodejs
  # Jupyter Ai
  - jupyter-ai
  - langchain-google-genai
  # developer tools
  - curl
  - make
  - wget
  - unzip
  # code development and linting
  - ruff
  # required for building hdstats
  - compilers 
 